apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  namespace: sharan
spec:
  containers:
  - name: nginx-resolver-dns
    image: busybox:1.28
    command:
      - sleep
      - "3600"